- src/PaperG/FirehoundBlob/FirehoundBlob.php
We need access to FirehoundBlob's budgets variable
PL-18500-PR
> Expose FirehoundBlob->budgets

- src/PaperG/FirehoundBlob/CampaignData/Budget.php
Added a new mobile key to Budget for mobile-specific budget
> Add mobile key to Budget

- .codeclimate.yml
- circle.yml
- composer.json
- composer.lock
- phpunit.xml
- src/PaperG/FirehoundBlob/CampaignData/CampaignGeoTargetingData.php
- src/PaperG/FirehoundBlob/CampaignData/Context.php
- src/PaperG/FirehoundBlob/CampaignData/Context/FacebookContext.php
- src/PaperG/FirehoundBlob/CampaignData/Targeting.php
- src/PaperG/FirehoundBlob/CampaignData/Targeting/AudienceTargeting.php
- src/PaperG/FirehoundBlob/Facebook/FacebookAdSet.php
- src/PaperG/FirehoundBlob/FirehoundBlob.php
- test/phpunit/bootstrap.php
- test/phpunit/src/PaperG/FirehoundBlob/BudgetTest.php
- test/phpunit/src/PaperG/FirehoundBlob/Context/FacebookContextTest.php
- test/phpunit/src/PaperG/FirehoundBlob/ContextTest.php
- test/phpunit/src/PaperG/FirehoundBlob/CreativeTest.php
- test/phpunit/src/PaperG/FirehoundBlob/ExchangeTargetingTest.php
- test/phpunit/src/PaperG/FirehoundBlob/FirehoundBlobTest.php
- test/phpunit/src/PaperG/FirehoundBlob/FirehoundBlobTestCase.php
- test/phpunit/src/PaperG/FirehoundBlob/PlatformTargetingTest.php
- test/phpunit/src/PaperG/FirehoundBlob/TargetingTest.php
Firehound blob has audience targeting within Context, but this should be moved.
This PR creates an AudienceTargeting item which resides within FirehoundBlob's
Targeting component.
PL-19114
> Add Audience Targeting into FirehoundBlob

- src/PaperG/FirehoundBlob/CampaignData/Creative.php
- src/PaperG/FirehoundBlob/FirehoundBlob.php
- test/phpunit/src/PaperG/FirehoundBlob/CreativeTest.php
- test/phpunit/src/PaperG/FirehoundBlob/FirehoundBlobTest.php
This commit makes FirehoundBlob contain multiple creatives instead of a single
one.
> Multiple Creatives

- test/phpunit/src/PaperG/FirehoundBlob/CreativeTest.php
This commit fixes a unit test.
> Fix unit test

- src/PaperG/FirehoundBlob/BasicInfo.php
- src/PaperG/FirehoundBlob/BlobInterface.php
- src/PaperG/FirehoundBlob/Facebook/FacebookBlob.php
- src/PaperG/FirehoundBlob/Facebook/FacebookCreative.php
- src/PaperG/FirehoundBlob/Facebook/FacebookCreativeData.php
- src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookAudienceTargeting.php
- src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookDemographicTargeting.php
- src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookGeographicTargeting.php
- src/PaperG/FirehoundBlob/Scenario.php
- src/PaperG/FirehoundBlob/ScenarioBlob.php
- src/PaperG/FirehoundBlob/Utility.php
- test/phpunit/src/PaperG/FirehoundBlob/BasicInfoTest.php
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/FacebookBlobTest.php
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/FacebookCreativeDataTest.php
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/FacebookCreativeTest.php
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookAudienceTargetingTest.php
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookDemographicTargetingTest.php
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookGeographicTargetingTest.php
- test/phpunit/src/PaperG/FirehoundBlob/FirehoundBlobTestCase.php
- test/phpunit/src/PaperG/UtilityTest.php
This commit:
* Adds a FacebookBlob class to the library.
* Adds classes for FacebookBlob objects
* Adds a Utility trait for convenience.
* Adds tests for everything
> Facebook Blob

- composer.json
- composer.lock
- src/PaperG/FirehoundBlob/Facebook/FacebookAdSet.php
This commit removes the unneeded dependency our library has on Facebook's SDK
> Remove Facebook SDK Dependency

- src/PaperG/FirehoundBlob/CampaignData/Budget.php
- src/PaperG/FirehoundBlob/Facebook/UnmanagedFacebookBlob.php
This commit adds budget to UnmanagedFacebookBlob, which was
previously missing.
> Add Missing Budget to UnmaangedFacebookBlob

- src/PaperG/FirehoundBlob/BasicInfo.php
- src/PaperG/FirehoundBlob/Facebook/FacebookCreative.php
- src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookAudienceTargeting.php
- src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookDemographicTargeting.php
- src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookGeographicTargeting.php
- src/PaperG/FirehoundBlob/Facebook/UnmanagedFacebookBlob.php
- src/PaperG/FirehoundBlob/Scenario.php
- src/PaperG/FirehoundBlob/ScenarioValidators/BasicInfoValidator.php
- src/PaperG/FirehoundBlob/ScenarioValidators/ScenarioValidator.php
- src/PaperG/FirehoundBlob/ScenarioValidators/UnmanagedFacebookValidator.php
- test/phpunit/src/PaperG/FirehoundBlob/ScenarioValidators/BasicInfoValidatorTest.php
- test/phpunit/src/PaperG/FirehoundBlob/ScenarioValidators/UnmanagedFacebookValidatorTest.php
Added scenario validators for Unmanaged facebook scenario.
This change added 2 unit tests for the basic info and unmanaged facebook blob.
> Add scenario validators

- src/PaperG/FirehoundBlob/Facebook/Creative/FacebookCarouselCreativeData.php
- src/PaperG/FirehoundBlob/Utility.php
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/Creative/FacebookCarouselCreativeTest.php
This commit adds a new object for FacebookCarousel to let us adjust certain
user settings.
PL-20580
> Add CarouselCreativeData

- src/PaperG/FirehoundBlob/Dcm/DcmCreativeAsset.php
- src/PaperG/FirehoundBlob/Dcm/UnmanagedDcmBlob.php
- src/PaperG/FirehoundBlob/Scenario.php
- src/PaperG/FirehoundBlob/ScenarioBlob.php
- test/phpunit/src/PaperG/FirehoundBlob/Dcm/UnmanagedDcmBlobTest.php
This commit adds the Unmanaged DCM object to Firehound Blob.
PL-20610
> Add DCM Blob

- src/PaperG/FirehoundBlob/Dcm/Validators/DcmCreativeAssetValidator.php
- src/PaperG/FirehoundBlob/Dcm/Validators/UnmanagedDcmBlobValidator.php
- src/PaperG/FirehoundBlob/ScenarioValidators/BasicInfoValidator.php
- src/PaperG/FirehoundBlob/ScenarioValidators/ScenarioValidator.php
- src/PaperG/FirehoundBlob/ScenarioValidators/UnmanagedFacebookValidator.php
- src/PaperG/FirehoundBlob/ScenarioValidators/ValidationResult.php
- test/phpunit/src/PaperG/FirehoundBlob/Dcm/Validators/DcmCreativeAssetValidatorTest.php
- test/phpunit/src/PaperG/FirehoundBlob/ScenarioValidators/BasicInfoValidatorTest.php
- test/phpunit/src/PaperG/FirehoundBlob/ScenarioValidators/UnmanagedFacebookValidatorTest.php
This commit adds validators for DCM.
> Add DCM Blob Validators

- src/PaperG/FirehoundBlob/BasicInfo.php
- test/phpunit/src/PaperG/FirehoundBlob/BasicInfoTest.php
Added a function in BasicInfo to append message.
> Add function to append metadata

- src/PaperG/FirehoundBlob/Dcm/DcmCreativeAsset.php
- src/PaperG/FirehoundBlob/Dcm/Validators/DcmCreativeAssetValidator.php
- src/PaperG/FirehoundBlob/Dcm/Validators/UnmanagedDcmBlobValidator.php
- test/phpunit/src/PaperG/FirehoundBlob/Dcm/UnmanagedDcmBlobTest.php
This commit adds fields that were missing from the DcmCreativeAsset object
which were previously missing.
PL-20672
> Extend DCM Creative Asset

- src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookDemographicTargeting.php
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookDemographicTargetingTest.php
Fixing FacebookDemographicTargeting to return default values.
> Fix FacebookDemographicTargeting

- src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookAudienceTargeting.php
- src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookGeographicTargeting.php
- src/PaperG/FirehoundBlob/ScenarioValidators/UnmanagedFacebookValidator.php
This commit adds some fixes to the UnmanagedFacebookValidator, which was too
strict on its checking.
PL-20876
> Validator Fixes

- src/PaperG/FirehoundBlob/Dcm/DcmCreativeAsset.php
- src/PaperG/FirehoundBlob/Dcm/Validators/DcmCreativeAssetValidator.php
- test/phpunit/src/PaperG/FirehoundBlob/Dcm/Validators/DcmCreativeAssetValidatorTest.php
We need ad set name for dcm creative assets for tracking.
> Add Ad Set Name to DcmCreativeAsset

- src/PaperG/FirehoundBlob/Dcm/Values/DcmObjectTypes.php
This commit adds DCM object types.
> Add DcmObjectTypes

- src/PaperG/FirehoundBlob/Facebook/UnmanagedFacebookBlob.php
The way we are gating facebook is via publication name, which is not
being passed through by unmanaged FB. This adds the name.
PL-21506
> UnmanagedFacebookBlob Publication Name

- src/PaperG/FirehoundBlob/CampaignData/Context/FacebookContext.php
- src/PaperG/FirehoundBlob/Facebook/UnmanagedFacebookBlob.php
- test/phpunit/src/PaperG/FirehoundBlob/Context/FacebookContextTest.php
> IG Actor ID field support

- src/PaperG/FirehoundBlob/CampaignData/Context/FacebookContext.php
- src/PaperG/FirehoundBlob/Facebook/UnmanagedFacebookBlob.php
- test/phpunit/src/PaperG/FirehoundBlob/Context/FacebookContextTest.php
> Adding Instagram actor id field to FH blob

- src/PaperG/FirehoundBlob/Facebook/Validators/FacebookCreativeValidator.php
- src/PaperG/FirehoundBlob/Schema/Facebook/facebookCreative.json
- src/PaperG/FirehoundBlob/Schema/Facebook/facebookCreativeData.json
- src/PaperG/FirehoundBlob/Schema/Facebook/facebookPrimaryCreativeData.json
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/Validators/FacebookCreativeValidatorTest.php
- test/phpunit/src/PaperG/FirehoundBlob/ScenarioValidators/UnmanagedFacebookValidatorTest.php
This commit updates facebook creative validation.
> Update Facebook Creative Validation

- src/PaperG/FirehoundBlob/Schema/Facebook/facebookAdSet.json
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/Validators/FacebookAdSetValidatorTest.php
This commit updates Facebook Ad Set Validation per the new placements.
> Update FacebookAdSet Validation

- src/PaperG/FirehoundBlob/Dcm/UnmanagedDcmBlob.php
- src/PaperG/FirehoundBlob/Facebook/UnmanagedFacebookBlob.php
- src/PaperG/FirehoundBlob/Schema/Dcm/unmanagedDcmBlob.json
- src/PaperG/FirehoundBlob/Schema/Facebook/Targeting/facebookAudienceTargeting.json
- src/PaperG/FirehoundBlob/Schema/Facebook/Targeting/facebookDemographicTargeting.json
- src/PaperG/FirehoundBlob/Schema/Facebook/facebookCreative.json
This commit adds platform to creative asset so we can still use the correct keys
for DCM.
PL-22018
> Add Platform to CreativeAsset

- src/PaperG/FirehoundBlob/AppNexus/AppNexusBidSetting.php
- src/PaperG/FirehoundBlob/AppNexus/AppNexusBlob.php
- src/PaperG/FirehoundBlob/AppNexus/AppNexusDaypartTargeting.php
- src/PaperG/FirehoundBlob/AppNexus/AppNexusPublisherCustomization.php
- src/PaperG/FirehoundBlob/AppNexus/AppNexusSegmentSetting.php
- src/PaperG/FirehoundBlob/AppNexus/Fields/AppNexusBidSettingFields.php
- src/PaperG/FirehoundBlob/AppNexus/Fields/AppNexusBlobFields.php
- src/PaperG/FirehoundBlob/AppNexus/Fields/AppNexusDaypartTargetingFields.php
- src/PaperG/FirehoundBlob/AppNexus/Fields/AppNexusPublisherCustomizationFields.php
- src/PaperG/FirehoundBlob/AppNexus/Fields/AppNexusSegmentSettingFields.php
- src/PaperG/FirehoundBlob/AppNexus/Validators/AppNexusBlobValidator.php
- src/PaperG/FirehoundBlob/CampaignData/CampaignGeoTargetingData.php
- src/PaperG/FirehoundBlob/CampaignData/CampaignGeotargetingDataFields.php
- src/PaperG/FirehoundBlob/CampaignData/CreativeBlob.php
- src/PaperG/FirehoundBlob/CampaignData/Fields/CreativeBlobFields.php
- src/PaperG/FirehoundBlob/CampaignData/Validators/CampaignGeotargetingDataValidator.php
- src/PaperG/FirehoundBlob/DataObject.php
- src/PaperG/FirehoundBlob/Schema/AppNexus/appNexusBlob.json
- src/PaperG/FirehoundBlob/Schema/AppNexus/bidSetting.json
- src/PaperG/FirehoundBlob/Schema/AppNexus/daypartTargeting.json
- src/PaperG/FirehoundBlob/Schema/AppNexus/publisherCustomization.json
- src/PaperG/FirehoundBlob/Schema/AppNexus/segmentSetting.json
- src/PaperG/FirehoundBlob/Schema/CampaignData/campaignGeotargetingData.json
- src/PaperG/FirehoundBlob/Schema/CampaignData/creative.json
- src/PaperG/FirehoundBlob/Schema/scenarioBlob.json
- test/phpunit/src/PaperG/FirehoundBlob/AppNexus/Validators/AppNexusBlobValidatorTest.php
- test/phpunit/src/PaperG/FirehoundBlob/CampaignData/Validators/CampaignGeotargetingDataValidatorTest.php
This commit adds the fields and objects needed to create AN campaigns via
Firehound Blob.
PL-22284
> Add AppNexus Scenario Blob

- src/PaperG/FirehoundBlob/AppNexus/AppNexusBlob.php
- src/PaperG/FirehoundBlob/AppNexus/Fields/AppNexusBlobFields.php
- src/PaperG/FirehoundBlob/Facebook/ManagedFacebookBlob.php
- src/PaperG/FirehoundBlob/Facebook/Targeting/FacebookAudienceTargeting.php
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/ManagedFacebookBlobTest.php
This commit adds industry id and uuid to the AppNexusBlob.
PL-22284
> Add Missing Fields to AppNexusBlob

- src/PaperG/FirehoundBlob/AppNexus/AppNexusBlob.php
- src/PaperG/FirehoundBlob/AppNexus/Values/AppNexusBlobType.php
- src/PaperG/FirehoundBlob/Schema/AppNexus/appNexusBlob.json
- test/phpunit/src/PaperG/FirehoundBlob/AppNexus/Validators/AppNexusBlobValidatorTest.php
This commit adds constants for the type of AN Blobs available.
PL-22284
> Add AN Blob Types

- src/PaperG/FirehoundBlob/AppNexus/AppNexusBlob.php
- src/PaperG/FirehoundBlob/AppNexus/Fields/AppNexusBlobFields.php
- src/PaperG/FirehoundBlob/ScenarioBlob.php
- src/PaperG/FirehoundBlob/Schema/AppNexus/appNexusBlob.json
- test/phpunit/src/PaperG/FirehoundBlob/ScenarioBlobTest.php
This commit:
* Allows ScenarioBlob::fromArray to handle AppNexusBlobs
* Adds a unit test for ScenarioBlob::fromArray
* removes uuid from AppNexusBlob, since that is part of BasicInfo
PL-22284
> Update AN Blob + ScenarioBlob

- src/PaperG/FirehoundBlob/AppNexus/AppNexusBlob.php
- src/PaperG/FirehoundBlob/AppNexus/Fields/AppNexusBlobFields.php
- src/PaperG/FirehoundBlob/AppNexus/Values/AppNexusCreativeDistributionTypes.php
This commit adds a new field to the AN blob, creativeDistributionType.
> Add Creative Distribution Type to AN Blob

- src/PaperG/FirehoundBlob/Schema/AppNexus/appNexusBlob.json
This commit updates the AN schema to reflect the new creativeDistributionType
field
> Update AN Schema

- src/PaperG/FirehoundBlob/Schema/AppNexus/appNexusBlob.json
- src/PaperG/FirehoundBlob/Schema/AppNexus/bidSetting.json
This allows more null values to be passed in.
PL-22278
> Update Json Validation

- src/PaperG/FirehoundBlob/Schema/AppNexus/daypartTargeting.json
- test/phpunit/src/PaperG/FirehoundBlob/AppNexus/Validators/AppNexusBlobValidatorTest.php
This commit allows daypart targeting to be a simple array.
> Daypart Targeting Validation Update

- src/PaperG/FirehoundBlob/Facebook/FacebookAdSet.php
- src/PaperG/FirehoundBlob/Facebook/ManagedFacebookBlob.php
- src/PaperG/FirehoundBlob/Facebook/UnmanagedFacebookBlob.php
This commit:
* Adds some missing functionality (CampaignObjective) to
UnmanagedFacebookBlob.
* Updates type hinting for ManagedFacebookBlob
* Adds toArray for FacebookAdSet
> Small Bug Fixes - Facebook

- src/PaperG/FirehoundBlob/Facebook/FacebookAdSet.php
- src/PaperG/FirehoundBlob/Schema/Facebook/facebookAdSet.json
This commit adds a new field to FacebookAdSet to allow the specification
of autobid.
PL-24177
> Add isAutoBid to FacebookAdSet

- composer.json
- composer.lock
- src/PaperG/FirehoundBlob/Dcm/UnmanagedDcmBlob.php
- test/phpunit/src/PaperG/FirehoundBlob/Dcm/Validators/UnmanagedDcmBlobValidatorTest.php
This commit updates our json schema library to the newest version, 5.2.1
Also fixes a unit test that wasn't doing anything.
> Update Json Schema Library

- composer.json
- composer.lock
- src/PaperG/FirehoundBlob/Dcm/UnmanagedDcmBlob.php
- test/phpunit/src/PaperG/FirehoundBlob/Dcm/Validators/UnmanagedDcmBlobValidatorTest.php
Reverts makethunder/firehound-blob#70
> Revert "Update Json Schema Library"

- src/PaperG/FirehoundBlob/AppNexus/AppNexusBlob.php
- src/PaperG/FirehoundBlob/AppNexus/Fields/AppNexusBlobFields.php
- src/PaperG/FirehoundBlob/Schema/AppNexus/appNexusBlob.json
- test/phpunit/src/PaperG/FirehoundBlob/AppNexus/Validators/AppNexusBlobValidatorTest.php
This commit adds the throttleMode field to AppNexus blobs.
PL-24536
> Add Throttle To AN

- src/PaperG/FirehoundBlob/AppNexus/AppNexusBlob.php
- src/PaperG/FirehoundBlob/AppNexus/Fields/AppNexusBlobFields.php
- src/PaperG/FirehoundBlob/Schema/AppNexus/appNexusBlob.json
This commit adds the ability to send mobile throttle settings.
PL-24536
> Add Mobile Throttle

- src/PaperG/FirehoundBlob/AppNexus/AppNexusDataIncludeFrame.php
- src/PaperG/FirehoundBlob/AppNexus/DimensionReference.php
- src/PaperG/FirehoundBlob/AppNexus/ExchangeCampaign.php
- src/PaperG/FirehoundBlob/CampaignData/CampaignAudienceGroups.php
- src/PaperG/FirehoundBlob/CampaignData/Context.php
Previously, we were dependant on certain classes being in certain
locations within PlaceLocal.  This commit brings those classes into this
library, so we can communicate more efficiently with Firehound.
PL-24536
> Minor Refactoring

- src/PaperG/FirehoundBlob/AppNexus/AppNexusBlob.php
- src/PaperG/FirehoundBlob/AppNexus/Fields/AppNexusBlobFields.php
- src/PaperG/FirehoundBlob/Schema/AppNexus/appNexusBlob.json
- test/phpunit/src/PaperG/FirehoundBlob/AppNexus/Validators/AppNexusBlobValidatorTest.php
This commit supports UserSubmitted as a field for AppNexus Blobs
PL-25099
> Support User Submitted

- src/PaperG/FirehoundBlob/Facebook/AdSets/GeneralFacebookAdSet.php
- src/PaperG/FirehoundBlob/Facebook/FacebookCreativeData.php
- src/PaperG/FirehoundBlob/Facebook/Fields/GeneralFacebookAdSetFields.php
- src/PaperG/FirehoundBlob/Facebook/Fields/GeneralFacebookBlobFields.php
- src/PaperG/FirehoundBlob/Facebook/GeneralFacebookBlob.php
- src/PaperG/FirehoundBlob/Facebook/Validators/GeneralFacebookBlobValidator.php
- src/PaperG/FirehoundBlob/Facebook/Values/FacebookPlatformTypes.php
- src/PaperG/FirehoundBlob/Schema/Facebook/facebookPrimaryCreativeData.json
- src/PaperG/FirehoundBlob/Schema/Facebook/generalFacebookAdSet.json
- src/PaperG/FirehoundBlob/Schema/Facebook/generalFacebookBlob.json
- test/phpunit/src/PaperG/FirehoundBlob/Facebook/Validators/GeneralFacebookBlobValidatorTest.php
This blob should better take care of both managed and unmanaged FB
scenarios.
This commit also adds ad unit id to FacebookCreativeData
PL-25385
> Introduce General Facebook Blob

- src/PaperG/FirehoundBlob/Scenario.php
We have a new scenario, Facebook Unmanaged v2, aka Facebook Unmanaged
Site Workflow.
PL-25385
> Add New Scenario

- src/PaperG/FirehoundBlob/Facebook/AdSets/GeneralFacebookAdSet.php
- src/PaperG/FirehoundBlob/Scenario.php
- src/PaperG/FirehoundBlob/ScenarioBlob.php
- test/phpunit/src/PaperG/FirehoundBlob/ScenarioBlobTest.php
> General Facebook Blob Fixes
